#!/bin/bash
RT=$PWD
rm -rf burn
mkdir -p burn
cd burn
cp -rf  $HOME/.config/xfce4 xfce4
cp -rf $HOME/.scripts scripts
cp $HOME/.profile profile
cd $RT
cp $HOME/.scripts/unburn unburn
cp $HOME/.scripts/superunburn superunburn
