#!/bin/bash
killall xbindkeys
if [ $1 == "revert" ] 
then
echo .xbindtemp > xbindkeysrc
xbindkeys
exit
fi
$(cat xbindkeysrc) > .xbindtemp
echo \" "(" "$@" ")" \" >> xbindkeysrc
xbindkeys -k | sed -n 5,6p >> xbindkeysrc
xbindkeys

