#!/bin/bash
ARG=2
PID=$(xinput | grep "TouchPad" | perl -pe 's/.*id=([^\s]+).*/$1/')
SID=$(xinput | grep "Touchscreen" | perl -pe 's/.*id=([^\s]+).*/$1/')
ID=$PID

case "$1" in
    0|d|disabled|off|disable|no)
	ARG=0;;
    1|e|enabled|on|enable|yes)
	ARG=1;;
    2|t|toggle|switch)
	ARG=2;;
    s|ts|screen|touch|touchscreen)
	ID=$SID;;
    p|pad|tp|touchpad|track|t|trackpad)
	ID=$PID;;
esac

case "$2" in
    0|d|disabled|off|disable|no)
	ARG=0;;
    1|e|enabled|on|enable|yes)
	ARG=1;;
    2|t|toggle|switch)
	ARG=2;;
    s|ts|screen|touch|touchscreen)
	ID=$SID;;
    p|pad|tp|touchpad|track|t|trackpad)
	ID=$PID;;
esac

mkdir -p .pointer

if [ $ID == $PID ] ; then
    LARG="$(cat .pointer/PID)"
fi
if [ $ID == $SID ] ; then
    LARG="$(cat .pointer/SID)"
fi


if [ $ARG == 2 -a $LARG == 1 ] ; then
    ARG=0
fi
if [ $ARG == 2 ] ; then
    ARG=1
fi


if [ $ID == $PID ] ; then
    echo $ARG > .pointer/PID
    if [ $ARG == 0 ] ; then
	xdotool mousemove 1920 1080
	fi
fi
if [ $ID == $SID ] ; then
    echo $ARG > .pointer/SID
fi


xinput set-prop $ID "Device Enabled" $ARG
